---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@cdca57260bffc365aaadd18b51b0efe8a7910d3d # main
